# Generated by Django 6.0.7 on 2026-08-03 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_remove_doctorprofile_clinic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.IntegerField(help_text='mmHg')),
                ('diastolic_bp', models.IntegerField(help_text='mmHg')),
                ('heart_rate', models.IntegerField(help_text='BPM')),
                ('blood_sugar', models.FloatField(help_text='mg/dL')),
                ('spo2_level', models.FloatField(help_text='%')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AIRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(help_text='Probability score 0.00 - 1.00')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=20)),
                ('predicted_condition', models.CharField(blank=True, max_length=150, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('vital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='core_app.patientvital')),
            ],
        ),
    ]
