# Generated by Django 6.0.7 on 2026-08-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='prescribed_by',
        ),
        migrations.AddField(
            model_name='medication',
            name='last_taken_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicine_name',
            field=models.CharField(max_length=100),
        ),
    ]
