# Generated by Django 6.0.7 on 2026-08-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_remove_medication_prescribed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.doctorprofile'),
        ),
    ]
