# Generated by Django 6.0.7 on 2026-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_diagnosticreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='919876543210', help_text='Enter phone number with country code without + (e.g. 919876543210)', max_length=15),
        ),
    ]
