# Generated by Django 6.0.7 on 2026-09-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCaseSheetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_impression', models.TextField()),
                ('recommended_action', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_sheet_notes', to='core_app.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
