# Generated by Django 6.0.7 on 2026-09-13 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_patientcasesheetnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_systolic_bp', models.IntegerField(default=90, help_text='Minimum safe systolic BP')),
                ('max_systolic_bp', models.IntegerField(default=140, help_text='Maximum safe systolic BP')),
                ('min_diastolic_bp', models.IntegerField(default=60, help_text='Minimum safe diastolic BP')),
                ('max_diastolic_bp', models.IntegerField(default=90, help_text='Maximum safe diastolic BP')),
                ('min_blood_sugar', models.FloatField(default=70, help_text='Minimum safe blood sugar')),
                ('max_blood_sugar', models.FloatField(default=180, help_text='Maximum safe blood sugar')),
                ('min_spo2', models.FloatField(default=90, help_text='Minimum safe oxygen saturation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='core_app.patient')),
            ],
        ),
    ]
