# Generated by Django 6.0.7 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_patientthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcasesheetnote',
            name='patient_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]